### ISSUE TITLE
[Bug] iOS - "Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown."	

### ISSUE THREAD

**Issue by WanftMoon** [Laerdal/Laerdal.Dfu#29]
**Describe the bug**
Project in xamarin forms with ble.net, when calling start in iOS, the following exception is thrown: 

"Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown."	

obs: Need guidance in case i'm missing something to setup the dfu correctly in iOS, because the same exception is not happening in Android. The process starts ok

```
  at Laerdal.Dfu.Bindings.iOS.DFUFirmware..ctor (Foundation.NSUrl urlToZipFile, Foundation.NSError& error) [0x0000d] in /Users/runner/work/1/s/Laerdal.Dfu.Bindings.iOS/obj/Release/xamarin.ios10/iOS/Laerdal.Dfu.Bindings.iOS/DFUFirmware.g.cs:119 
  at Laerdal.Dfu.DfuServiceInitiatorDelegate..ctor (Laerdal.Dfu.DfuInstallation dfuInstallation) [0x00010] in /_/Laerdal.Dfu/Platforms/iOS/DfuServiceInitiatorDelegate.cs:29 
  at Laerdal.Dfu.DfuInstallation.Start (Laerdal.Dfu.DfuConfiguration configuration) [0x00034] in /_/Laerdal.Dfu/Platforms/iOS/DfuInstallation.cs:33 
  at Viewmodel.BleConnectedDeviceViewModel.FlashDevice (System.Object arg) [0x0010c] 
```

**To Reproduce**
1. Create Xamarin.Forms project
2. Include ble library and configure it to scan a device
3. Add Laerdal.Dfu
4. Configure install
```
 dfuInstall = new DfuInstallation(deviceAddress /*59:A1:A6:62:41:7A*/, fi.FullName);

dfuInstall.DfuErrorReceived += OnDfuErrorOccured;
dfuInstall.DfuStateChanged += OnDfuStateChanged;
dfuInstall.DfuProgressChanged += OnDfuProgressChanged;

dfuInstall.Start(new DfuConfiguration() { DisableNotification = true, Foreground = false });
```

**Expected behavior**
The install to start like it does in Android.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Versions
 -- ble.net 1.2.1
 -- Laerdal.Dfu 1.27.2-xamarin-10.45630
 -- Xamarin.Essentials - 1.8.1
 -- Xamarin.Forms - 5.0.0.2622

**Smartphone (please complete the following information):**
 - Device: iPhone 8+
 - OS: 16
 - Browser N/A
 - Version N/A

**Additional context**
N/A

**Comment by schneifa** [comment]
We are currently this issue in #27

**Comment by WanftMoon** [comment]
Oki, for those interested. The issue is in: https://github.com/Laerdal/Laerdal.Dfu.Bindings.iOS/tree/master

@schneifa @framinosona @ksidirop-laerdal 

I re-did the bindings locally, so if anyone that maintain the project and would like to check the changes below and also update all the native binding and references, that would make people happy.

1. Project linking against a xcframework - set to no binding Embedding (right now is embedding)
`<NoBindingEmbedding>true</NoBindingEmbedding>`

2. The api definition needs tweeking:
a. Interfaces just need the BaseType (the exception reported was because there were [Model] everywhere which generates a model with no code besides the exception being thrown
```
// @interface DFUFirmware : NSObject
[BaseType(typeof(NSObject), Name = "_TtC9NordicDFU11DFUFirmware")]
[DisableDefaultCtor]
interface DFUFirmware
```
b. Protocols, there are only 4 of them. I've left the [BaseType][Protocol][Model]
```
// @protocol DFUPeripheralSelectorDelegate
[BaseType(typeof(NSObject), Name = "_TtP9NordicDFU29DFUPeripheralSelectorDelegate_")]
[Protocol(Name = "_TtP9NordicDFU29DFUPeripheralSelectorDelegate_")]
[Model(Name = "_TtP9NordicDFU29DFUPeripheralSelectorDelegate_")]
interface DFUPeripheralSelectorDelegate
```

att.

**Comment by ISSPRO-Eng** [comment]
Thank you for the work @WanftMoon !!!! Hopefully the local project is updated soon :)

**Comment by algrm** [comment]
@WanftMoon thanks for your insights. I don't think it fully applies here, as AppDefinition.cs here is different from the one in Laerdal.Dfu.Bindings.iOS. And thanks @framinosona for sharing this work, extremely useful to me.
After several days on this topic, here is what I did:

- Rebuild separate nuget packages for both bindings, from Laerdal's sources. I removed the net6 support and applied @WanftMoon advices on the iOS package. The iOS library must be build on a Mac.
- Create a new MAUI/.NET 8 library and copy Laerdal.Dfu source in it. This is mostly a matter or putting the files in different folders. I use the binding packages as dependencies.

I stumbled today on another problem (undefined symbol for the ios Nordic functions). I solved it by changing the path of the framework dependencies and make them point to the arm64 framework in the Carthage folder.

I hope this might help. Too many changes to make a PR but I'll be happy to share my work if asked.

**Comment by neicureuil** [comment]
Hi, 
I'm facing the same issue, I tried to compile the bindings my self and following the instructions of @WanftMoon  but I don't really understand what need to be change in the iOS binding.

I have tried to remove the "[Model]" attribute but same error : "Foundation.You_Should_Not_Call_base_In_This_Method".

Can you provide a patch or help please ?

**Comment by WanftMoon** [comment]
> Hi, I'm facing the same issue, I tried to compile the bindings my self and following the instructions of @WanftMoon but I don't really understand what need to be change in the iOS binding.
> 
> I have tried to remove the "[Model]" attribute but same error : "Foundation.You_Should_Not_Call_base_In_This_Method".
> 
> Can you provide a patch or help please ?

just make sure you edit your api definition file as follows:

a. **Interfaces** just need the BaseType (the exception reported was because there were [Model] everywhere which generates a model with no code besides the exception being thrown
```
// @interface DFUFirmware : NSObject
[BaseType(typeof(NSObject), Name = "_TtC9NordicDFU11DFUFirmware")]
[DisableDefaultCtor]
interface DFUFirmware
```
b. **Protocols**, there are only 4 of them. I've left the [BaseType][Protocol][Model]
```
// @protocol DFUPeripheralSelectorDelegate
[BaseType(typeof(NSObject), Name = "_TtP9NordicDFU29DFUPeripheralSelectorDelegate_")]
[Protocol(Name = "_TtP9NordicDFU29DFUPeripheralSelectorDelegate_")]
[Model(Name = "_TtP9NordicDFU29DFUPeripheralSelectorDelegate_")]
interface DFUPeripheralSelectorDelegate
```

**Comment by neicureuil** [comment]
That's what I did but I got the same error :
```
[0:] Exception choosing file: Foundation.You_Should_Not_Call_base_In_This_Method: Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown.
  at Laerdal.Dfu.Bindings.iOS.DFUFirmware..ctor (Foundation.NSUrl urlToZipFile, Foundation.NSError& error) [0x0000d] in /Users/runner/work/1/s/Laerdal.Dfu.Bindings.iOS/obj/Release/xamarin.ios10/iOS/Laerdal.Dfu.Bindings.iOS/DFUFirmware.g.cs:119 
  at Laerdal.Dfu.DfuServiceInitiatorDelegate..ctor (Laerdal.Dfu.DfuInstallation dfuInstallation) [0x00010] in /Users/neicureuil/Documents/Laerdal.Dfu/Laerdal.Dfu/Platforms/iOS/DfuServiceInitiatorDelegate.cs:29 
  at Laerdal.Dfu.DfuInstallation.Start (Laerdal.Dfu.DfuConfiguration configuration) [0x00034] in /Users/neicureuil/Documents/Laerdal.Dfu/Laerdal.Dfu/Platforms/iOS/DfuInstallation.cs:33 
  at Nordic.Sdk.Impl.Dfu.DfuManager.Start (System.String deviceAddress, System.String firmwareZipFile) [0x00062] in C:\Users
```

Here is my modified ApiDefinition.cs, do you see anything that I forgot ? [https://gist.github.com/neicureuil/d2893c384437422c5a4f1c6bbb20f677](url)

**Comment by WanftMoon** [comment]
> That's what I did but I got the same error :
> ```
> [0:] Exception choosing file: Foundation.You_Should_Not_Call_base_In_This_Method: Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown.
>   at Laerdal.Dfu.Bindings.iOS.DFUFirmware..ctor (Foundation.NSUrl urlToZipFile, Foundation.NSError& error) [0x0000d] in /Users/runner/work/1/s/Laerdal.Dfu.Bindings.iOS/obj/Release/xamarin.ios10/iOS/Laerdal.Dfu.Bindings.iOS/DFUFirmware.g.cs:119 
>   at Laerdal.Dfu.DfuServiceInitiatorDelegate..ctor (Laerdal.Dfu.DfuInstallation dfuInstallation) [0x00010] in /Users/neicureuil/Documents/Laerdal.Dfu/Laerdal.Dfu/Platforms/iOS/DfuServiceInitiatorDelegate.cs:29 
>   at Laerdal.Dfu.DfuInstallation.Start (Laerdal.Dfu.DfuConfiguration configuration) [0x00034] in /Users/neicureuil/Documents/Laerdal.Dfu/Laerdal.Dfu/Platforms/iOS/DfuInstallation.cs:33 
>   at Nordic.Sdk.Impl.Dfu.DfuManager.Start (System.String deviceAddress, System.String firmwareZipFile) [0x00062] in C:\Users
> ```
> 
> Here is my modified ApiDefinition.cs, do you see anything that I forgot ? [https://gist.github.com/neicureuil/d2893c384437422c5a4f1c6bbb20f677](url)

Looking at your file, you didn't. You have several classes that maps the sdk interfaces marked as protocol. 

```
// @interface DFUFirmware : NSObject
        [BaseType (typeof(NSObject), Name = "_TtC13iOSDFULibrary11DFUFirmware")]
        [Protocol (Name = "_TtC13iOSDFULibrary11DFUFirmware")]
        [DisableDefaultCtor]
        interface DFUFirmware
```

**Comment by neicureuil** [comment]
Thanks for your help, it was a nuget cache issue.
With your modification, I got an other error : 
```
[0:] Exception choosing file: System.Exception: Could not create an native instance of the type 'Laerdal.Dfu.Bindings.iOS.DFUFirmware': the native class hasn't been loaded.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
  at Foundation.NSObject.InitializeObject (System.Boolean alloced) [0x000b2] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/src/Xamarin.iOS/Foundation/NSObject2.cs:360 
  at Foundation.NSObject..ctor (Foundation.NSObjectFlag x) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/src/Xamarin.iOS/Foundation/NSObject2.cs:201 
```

It seems that the native lib isn't loaded. Do you have any idea why I get this error ?

**Comment by WanftMoon** [comment]
> Thanks for your help, it was a nuget cache issue. With your modification, I got an other error :
> 
> ```
> [0:] Exception choosing file: System.Exception: Could not create an native instance of the type 'Laerdal.Dfu.Bindings.iOS.DFUFirmware': the native class hasn't been loaded.
> It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
>   at Foundation.NSObject.InitializeObject (System.Boolean alloced) [0x000b2] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/src/Xamarin.iOS/Foundation/NSObject2.cs:360 
>   at Foundation.NSObject..ctor (Foundation.NSObjectFlag x) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/16.4.0.23/src/Xamarin.iOS/Foundation/NSObject2.cs:201 
> ```
> 
> It seems that the native lib isn't loaded. Do you have any idea why I get this error ?

You might want to check that the xcframework is being copied to the correct location (referencing the ios native binding in your ios project might help).
Also, check that native binding is not embedding. 
`<NoBindingEmbedding>true</NoBindingEmbedding>`

**Comment by ISSPRO-Eng** [comment]
@algrm or @neicureuil 

Any chance you could share the updated Nuget Package with me? I do not have any experience on building or editing NuGet Packages, so I am still waiting on an update to the master Nuget.

**Comment by ISSPRO-Eng** [comment]
Detected package downgrade: Laerdal.Dfu.Bindings.iOS from 4.13.0.43857 to 4.13.0.88. Reference the package directly from the project to select a different version. 

@algrm @WanftMoon @neicureuil 

Getting this message when trying to add a newly built iOS Bindings Library to my app to replace the 4.13.0.43857 version that Laerdal.Dfu 1.27.8 relies on

**Comment by ISSPRO-Eng** [comment]
> > Detected package downgrade: Laerdal.Dfu.Bindings.iOS from 4.13.0.43857 to 4.13.0.88. Reference the package directly from the project to select a different version.
> > @algrm @WanftMoon @neicureuil
> > Getting this message when trying to add a newly built iOS Bindings Library to my app to replace the 4.13.0.43857 version that Laerdal.Dfu 1.27.8 relies on
> 
> Don't use both, since you build a native binding, you will need to do the same with the wrapper (laerdal.dfu). Just get Laerdal.Dfu code, add it to the solution, then update the references.

Guess I am a bit confused. I cloned both the Laerdal.Dfu Library and the iOS Binding Library. I updated the Bindings Library to use your changes. How would I then rebuild the Laerdal.Dfu Nuget to use the updated bindings library I made? Sorry a bit new to this and normally just use third party sources since I am super fresh to C#

**Comment by WanftMoon** [comment]
> > > Detected package downgrade: Laerdal.Dfu.Bindings.iOS from 4.13.0.43857 to 4.13.0.88. Reference the package directly from the project to select a different version.
> > > @algrm @WanftMoon @neicureuil
> > > Getting this message when trying to add a newly built iOS Bindings Library to my app to replace the 4.13.0.43857 version that Laerdal.Dfu 1.27.8 relies on
> > 
> > 
> > Don't use both, since you build a native binding, you will need to do the same with the wrapper (laerdal.dfu). Just get Laerdal.Dfu code, add it to the solution, then update the references.
> 
> Guess I am a bit confused. I cloned both the Laerdal.Dfu Library and the iOS Binding Library. I updated the Bindings Library to use your changes. How would I then rebuild the Laerdal.Dfu Nuget to use the updated bindings library I made? Sorry a bit new to this and normally just use third party sources since I am super fresh to C#

Just edit the csproj of the Laerdal.Dfu to reference your bindings.

```
<ItemGroup Condition="$(TargetFramework.StartsWith('xamarin.ios'))">
        <Compile Include="Platforms\iOS\*.cs" />
	<!-- this is the old reference <PackageReference Include="Laerdal.Dfu.Bindings.iOS" Version="4.13.0-xamarin.43596" />-->
	<ProjectReference Include="..\MY_PATH_TO_MY_NATIVE_BINDINGS\Dfu.Bindings.iOS.csproj" />
</ItemGroup>
```

**Comment by ISSPRO-Eng** [comment]
> > > > Detected package downgrade: Laerdal.Dfu.Bindings.iOS from 4.13.0.43857 to 4.13.0.88. Reference the package directly from the project to select a different version.
> > > > @algrm @WanftMoon @neicureuil
> > > > Getting this message when trying to add a newly built iOS Bindings Library to my app to replace the 4.13.0.43857 version that Laerdal.Dfu 1.27.8 relies on
> > > 
> > > 
> > > Don't use both, since you build a native binding, you will need to do the same with the wrapper (laerdal.dfu). Just get Laerdal.Dfu code, add it to the solution, then update the references.
> > 
> > 
> > Guess I am a bit confused. I cloned both the Laerdal.Dfu Library and the iOS Binding Library. I updated the Bindings Library to use your changes. How would I then rebuild the Laerdal.Dfu Nuget to use the updated bindings library I made? Sorry a bit new to this and normally just use third party sources since I am super fresh to C#
> 
> Just edit the csproj of the Laerdal.Dfu to reference your bindings.
> 
> ```
> <ItemGroup Condition="$(TargetFramework.StartsWith('xamarin.ios'))">
>         <Compile Include="Platforms\iOS\*.cs" />
> 	
> 	<ProjectReference Include="..\MY_PATH_TO_MY_NATIVE_BINDINGS\Dfu.Bindings.iOS.csproj" />
> </ItemGroup>
> ```

Okay thanks. I see the current package version of the cloned Laerdal Dfu project is 0.0.2. Did this need any change since the latest Nuget is 1.27.8 or can that just stay the same

**Comment by ISSPRO-Eng** [comment]
@WanftMoon This about right?

` 
    <PropertyGroup Condition=" $(TargetFramework.ToLower().StartsWith('xamarin.ios')) ">
        <IsBindingProject>true</IsBindingProject>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <MtouchExtraArgs>-v -v -v -v</MtouchExtraArgs>
        
        
        <NoWarn>CS0114</NoWarn>
    </PropertyGroup>
    <ItemGroup Condition=" $(TargetFramework.ToLower().StartsWith('xamarin.ios')) ">
        <Reference Include="Xamarin.iOS" />
        <Reference Include="netstandard" />
        <Compile Include="iOS\*.cs" />
        <Compile Include="iOS\Specific\*.cs" />
        <ObjcBindingCoreSource Include="iOS\ObjcBinding\Structs.cs" />
        <ObjcBindingApiDefinition Include="iOS\ObjcBinding\ApiDefinition.cs" />
        <PackageReference Include="Xamarin.iOS.SwiftRuntimeSupport" Version="0.2.1" />
        <PackageReference Include="Xamarin.Swift" Version="1.0.11" />
        <ProjectReference Include="\Users\Documents\GitHub\nuget_repo\Laerdal.Dfu.Bindings.iOS\Laerdal.Dfu.Bindings.iOS\Dfu.Bindings.iOS.csproj" />
    </ItemGroup>

    <Target Condition=" $(TargetFramework.ToLower().StartsWith('xamarin.ios')) AND $(DownloadNativeFiles)" Name="_DownloadIosNativeFiles" BeforeTargets="BeforeBuild">
        <WriteLinesToFile File="iOS\Carthage\Cartfile" Lines="github &quot;NordicSemiconductor/IOS-Pods-DFU-Library&quot; &quot;4.13.0&quot;" Overwrite="true" />
        <Exec WorkingDirectory="iOS\Carthage\" Command="carthage update --use-xcframeworks --platform iOS" />
        <Exec Condition=" $(RunSharpie)" Command="sharpie bind -sdk iphoneos -o iOS/Sharpie --namespace=Laerdal.Dfu.iOS -f iOS/Carthage/Carthage/Build/iOSDFULibrary.xcframework/ios-arm64/iOSDFULibrary.framework" EnvironmentVariables="GITHUB_ACCESS_TOKEN=$(LaerdalGithubAccessToken)" />

        
        
        
        
        <Touch Files="iOS/Carthage/Carthage/Build/iOSDFULibrary.xcframework/.keepme_in_git_otherwise_azure_pipelines_will_break" AlwaysCreate="true" />
        <Touch Files="iOS/Carthage/Carthage/Build/ZIPFoundation.xcframework/.keepme_in_git_otherwise_azure_pipelines_will_break" AlwaysCreate="true" />
    </Target>

    <ItemGroup Condition=" $(TargetFramework.ToLower().StartsWith('xamarin.ios')) ">

        
        <NativeReference Include="iOS/Carthage/Carthage/Build/iOSDFULibrary.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
            <Frameworks>Foundation</Frameworks>
        </NativeReference>

        
        <NativeReference Include="iOS/Carthage/Carthage/Build/ZIPFoundation.xcframework">
            <Kind>Framework</Kind>
            <SmartLink>False</SmartLink>
            <Frameworks>Foundation</Frameworks>
        </NativeReference>

    </ItemGroup>`

**Comment by ISSPRO-Eng** [comment]
@WanftMoon This look about right?
'
 <ItemGroup Condition=" $(TargetFramework.ToLower().StartsWith('xamarin.ios')) ">
        <Reference Include="Xamarin.iOS" />
        <Reference Include="netstandard" />
        <Compile Include="iOS\*.cs" />
        <Compile Include="iOS\Specific\*.cs" />
        <ObjcBindingCoreSource Include="iOS\ObjcBinding\Structs.cs" />
        <ObjcBindingApiDefinition Include="iOS\ObjcBinding\ApiDefinition.cs" />
        <PackageReference Include="Xamarin.iOS.SwiftRuntimeSupport" Version="0.2.1" />
        <PackageReference Include="Xamarin.Swift" Version="1.0.11" />
        <ProjectReference Include="\Users\isspro\Documents\GitHub\nuget_repo\Laerdal.Dfu.Bindings.iOS\Laerdal.Dfu.Bindings.iOS\Dfu.Bindings.iOS.csproj" />
    </ItemGroup>
'

**Comment by WanftMoon** [comment]
> > > > > Detected package downgrade: Laerdal.Dfu.Bindings.iOS from 4.13.0.43857 to 4.13.0.88. Reference the package directly from the project to select a different version.
> > > > > @algrm @WanftMoon @neicureuil
> > > > > Getting this message when trying to add a newly built iOS Bindings Library to my app to replace the 4.13.0.43857 version that Laerdal.Dfu 1.27.8 relies on
> > > > 
> > > > 
> > > > Don't use both, since you build a native binding, you will need to do the same with the wrapper (laerdal.dfu). Just get Laerdal.Dfu code, add it to the solution, then update the references.
> > > 
> > > 
> > > Guess I am a bit confused. I cloned both the Laerdal.Dfu Library and the iOS Binding Library. I updated the Bindings Library to use your changes. How would I then rebuild the Laerdal.Dfu Nuget to use the updated bindings library I made? Sorry a bit new to this and normally just use third party sources since I am super fresh to C#
> > 
> > 
> > Just edit the csproj of the Laerdal.Dfu to reference your bindings.
> > ```
> > <ItemGroup Condition="$(TargetFramework.StartsWith('xamarin.ios'))">
> >         <Compile Include="Platforms\iOS\*.cs" />
> > 	
> > 	<ProjectReference Include="..\MY_PATH_TO_MY_NATIVE_BINDINGS\Dfu.Bindings.iOS.csproj" />
> > </ItemGroup>
> > ```
> 
> Okay thanks. I see the current package version of the cloned Laerdal Dfu project is 0.0.2. Did this need any change since the latest Nuget is 1.27.8 or can that just stay the same
> 
> Also, got this when referencing the csproj library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1982,5): warning : The referenced project 'Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu.Bindings.iOS/Laerdal.Dfu.Bindings.iOS/Dfu.Bindings.iOS.csproj' does not exist. [/Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu/Laerdal.Dfu/Laerdal.Dfu.csproj]

`The referenced project ... does not exist` looks like your path is wrong.

**Comment by ISSPRO-Eng** [comment]
> > > > > > Detected package downgrade: Laerdal.Dfu.Bindings.iOS from 4.13.0.43857 to 4.13.0.88. Reference the package directly from the project to select a different version.
> > > > > > @algrm @WanftMoon @neicureuil
> > > > > > Getting this message when trying to add a newly built iOS Bindings Library to my app to replace the 4.13.0.43857 version that Laerdal.Dfu 1.27.8 relies on
> > > > > 
> > > > > 
> > > > > Don't use both, since you build a native binding, you will need to do the same with the wrapper (laerdal.dfu). Just get Laerdal.Dfu code, add it to the solution, then update the references.
> > > > 
> > > > 
> > > > Guess I am a bit confused. I cloned both the Laerdal.Dfu Library and the iOS Binding Library. I updated the Bindings Library to use your changes. How would I then rebuild the Laerdal.Dfu Nuget to use the updated bindings library I made? Sorry a bit new to this and normally just use third party sources since I am super fresh to C#
> > > 
> > > 
> > > Just edit the csproj of the Laerdal.Dfu to reference your bindings.
> > > ```
> > > <ItemGroup Condition="$(TargetFramework.StartsWith('xamarin.ios'))">
> > >         <Compile Include="Platforms\iOS\*.cs" />
> > > 	
> > > 	<ProjectReference Include="..\MY_PATH_TO_MY_NATIVE_BINDINGS\Dfu.Bindings.iOS.csproj" />
> > > </ItemGroup>
> > > ```
> > 
> > 
> > Okay thanks. I see the current package version of the cloned Laerdal Dfu project is 0.0.2. Did this need any change since the latest Nuget is 1.27.8 or can that just stay the same
> > Also, got this when referencing the csproj library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1982,5): warning : The referenced project 'Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu.Bindings.iOS/Laerdal.Dfu.Bindings.iOS/Dfu.Bindings.iOS.csproj' does not exist. [/Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu/Laerdal.Dfu/Laerdal.Dfu.csproj]
> 
> `The referenced project ... does not exist` looks like your path is wrong.
![image](https://github.com/Laerdal/Laerdal.Dfu/assets/97247069/0b6b9915-3421-47f1-807b-86e030ee6fec)

**Comment by ISSPRO-Eng** [comment]
> > > > > > Detected package downgrade: Laerdal.Dfu.Bindings.iOS from 4.13.0.43857 to 4.13.0.88. Reference the package directly from the project to select a different version.
> > > > > > @algrm @WanftMoon @neicureuil
> > > > > > Getting this message when trying to add a newly built iOS Bindings Library to my app to replace the 4.13.0.43857 version that Laerdal.Dfu 1.27.8 relies on
> > > > > 
> > > > > 
> > > > > Don't use both, since you build a native binding, you will need to do the same with the wrapper (laerdal.dfu). Just get Laerdal.Dfu code, add it to the solution, then update the references.
> > > > 
> > > > 
> > > > Guess I am a bit confused. I cloned both the Laerdal.Dfu Library and the iOS Binding Library. I updated the Bindings Library to use your changes. How would I then rebuild the Laerdal.Dfu Nuget to use the updated bindings library I made? Sorry a bit new to this and normally just use third party sources since I am super fresh to C#
> > > 
> > > 
> > > Just edit the csproj of the Laerdal.Dfu to reference your bindings.
> > > ```
> > > <ItemGroup Condition="$(TargetFramework.StartsWith('xamarin.ios'))">
> > >         <Compile Include="Platforms\iOS\*.cs" />
> > > 	
> > > 	<ProjectReference Include="..\MY_PATH_TO_MY_NATIVE_BINDINGS\Dfu.Bindings.iOS.csproj" />
> > > </ItemGroup>
> > > ```
> > 
> > 
> > Okay thanks. I see the current package version of the cloned Laerdal Dfu project is 0.0.2. Did this need any change since the latest Nuget is 1.27.8 or can that just stay the same
> > Also, got this when referencing the csproj library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/Microsoft.Common.CurrentVersion.targets(1982,5): warning : The referenced project 'Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu.Bindings.iOS/Laerdal.Dfu.Bindings.iOS/Dfu.Bindings.iOS.csproj' does not exist. [/Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu/Laerdal.Dfu/Laerdal.Dfu.csproj]
> 
> `The referenced project ... does not exist` looks like your path is wrong.

Updated the reference. Was missing a word. Now here

/Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error : Invalid framework identifier ''. [/Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu/Laerdal.Dfu/Laerdal.Dfu.csproj]
Done Building Project "/Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu/Laerdal.Dfu/Laerdal.Dfu.csproj" (Restore target(s)) -- FAILED.

Build FAILED.

"/Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu/Laerdal.Dfu/Laerdal.Dfu.csproj" (Restore target) (1) ->
(Restore target) -> 
  /Library/Frameworks/Mono.framework/Versions/6.12.0/lib/mono/msbuild/Current/bin/NuGet.targets(131,5): error : Invalid framework identifier ''. [/Users/isspro/Documents/GitHub/nuget_repo/Laerdal.Dfu/Laerdal.Dfu/Laerdal.Dfu.csproj]

**Comment by ISSPRO-Eng** [comment]
@WanftMoon What branch did you use? I had been on the main branch and am now seeing it is not even updated for .NET 7 which is what I am using. Is the develop branch the one that you used?

**Comment by WanftMoon** [comment]
> @WanftMoon What branch did you use? I had been on the main branch and am now seeing it is not even updated for .NET 7 which is what I am using. Is the develop branch the one that you used?

My project is xamarin forms.

**Comment by ISSPRO-Eng** [comment]
> > @WanftMoon What branch did you use? I had been on the main branch and am now seeing it is not even updated for .NET 7 which is what I am using. Is the develop branch the one that you used?
> 
> My project is xamarin forms.

Makes sense. Pretty sure one of the older Nuget Packages worked straight out of the box (I think 0.0.7 works fine for my Xamarin Forms application).

**Comment by ISSPRO-Eng** [comment]
@algrm @neicureuil Did you guys use this for .NET Maui?

**Comment by ISSPRO-Eng** [comment]
For anyone trying to make this work in a .NET Maui app, I have two repos started.

https://github.com/ISSPRO-Eng/Laerdal.Dfu.git and https://github.com/ISSPRO-Eng/Laerdal.Dfu.Bindings.iOS.git

I was able to build the iOS bindings project and reference them in the main dfu library. Still getting the You should not call base error though so work is still being done. I have versioned the bindings as 4.13.0.88 and the DFU Library as 1.0.0

**Comment by ISSPRO-Eng** [comment]
Has anyone had any luck with the newer release of the nuget in fixing this issue or still on going?

**Comment by framinosona** [comment]
Hi, we've had a bit of time this morning to work on this. Can you guys test https://www.nuget.org/packages/Laerdal.Dfu/1.27.62 ?

**Comment by ISSPRO-Eng** [comment]
@framinosona Still getting the error: Foundation.You_Should_Not_Call_base_In_This_Method: Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method' was thrown.
   at Laerdal.Dfu.Bindings.iOS.DFUFirmware..ctor(NSUrl urlToZipFile, NSError& error)

**Comment by ISSPRO-Eng** [comment]
@ksidirop-laerdal Now we have this error on our end with the newest release of 1.27.73

2024-05-15 13:48:57.581 MauiAttributeProgrammer[6332:4813024] System.Exception: Could not initialize an instance of the type 'Foundation.NSUuid': the native 'initWithUUIDString:' method returned nil.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.
2024-05-15 13:48:57.581 MauiAttributeProgrammer[6332:4813024]    at Foundation.NSObject.InitializeHandle(NativeHandle handle, String initSelector) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:line 661
2024-05-15 13:48:57.581 MauiAttributeProgrammer[6332:4813024]    at Foundation.NSUuid..ctor(String str) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/Foundation/NSUuid.g.cs:line 104
   at Laerdal.Dfu.DfuInstallation.Start()
2024-05-15 13:48:57.581 MauiAttributeProgrammer[6332:4813024]    at MauiAttributeProgrammer.ViewModels.DFUPageViewModel.Start() in /Users/isspro/Documents/GitHub/MauiAttributeProgrammer/MauiAttributeProgrammer/ViewModels/DFUPageViewModel.cs:line 32

**Comment by framinosona** [comment]
Cross-referencing #27 (original report, same exception) and #14 (older related `NSUrl` ctor binding issue). This thread has the most complete diagnosis: stray `[Model]` attributes on plain interfaces in `Laerdal.Dfu.Bindings.iOS/ApiDefinition.cs` produced an empty runtime model for `DFUFirmware`. @WanftMoon's patch is correct; v1.27.62 attempted to ship it but the NuGet build regressed and re-added the `[Model]` attributes (per @ISSPRO-Eng's confirmation above). Checked the current source on `framinosona/refresh`: `[Model]` is not present on `DFUFirmware` today, so this looks fixed in source again — but needs verification against a real published NuGet + device before closing. Labeling as `bug` and keeping open.
