### ISSUE TITLE
dfu exception on android (maui)

### ISSUE THREAD

**Issue by siki411** [Laerdal/Laerdal.Dfu#50]
i am facing this issue while updating firmware it keep throwing this exception though i have added proguard rules in platforms andriod resources but it still showing it, 

**DfuArchiveInputStream] Manifest failed to be parsed. Did you add
[DfuArchiveInputStream] -keep class no.nordicsemi.android.dfu.** { *; }
**[DfuArchiveInputStream] to your proguard rules?
[DfuBaseService] An exception occurred while calculating file size
[DfuBaseService] java.io.IOException: The ZIP file must contain an Application, a Soft Device and/or a Bootloader.****
[DfuBaseService] at no.nordicsemi.android.dfu.internal.ArchiveInputStream.<init>(ArchiveInputStream.java:269)
[DfuBaseService] at no.nordicsemi.android.dfu.DfuBaseService.openInputStream(DfuBaseService.java:1457)
[DfuBaseService] at no.nordicsemi.android.dfu.DfuBaseService.onHandleIntent(DfuBaseService.java:1201)
[DfuBaseService] at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
[DfuBaseService] at android.os.Handler.dispatchMessage(Handler.java:106)
[DfuBaseService] at android.os.Looper.loop(Looper.java:246)
[DfuBaseService] at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Pmr-precure** [comment]
Did you ever get a solution for this? - im at this point now :)

**Comment by siki411** [comment]
i am sorry i was unable to find solution

**Comment by framinosona** [comment]
Duplicate of #48 — same underlying symptom (`ArchiveInputStream` manifest parse failure / missing Application-SoftDevice-Bootloader), which points to an invalid/malformed DFU zip package rather than a library bug. Closing as duplicate; see #48 for details.
